name: Flow
on: push

jobs:
  build-web:
    name: Build (Web)
    runs-on: ubuntu-latest
    container: ghcr.io/geng-engine/cargo-geng
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: cargo geng build --release --platform web
      - name: Upload artifacts (web)
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: target/geng

  deploy:
    name: Deploy Github Pages
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'nertsal'
    runs-on: ubuntu-latest
    needs:
      - build-web
    environment:
      name: main
      url: https://nertsal.github.io/drill-above
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web

  deploy-dev:
    name: Deploy Github Pages (Dev)
    if: github.ref == 'refs/heads/dev' && github.repository_owner == 'nertsal'
    runs-on: ubuntu-latest
    needs:
      - build-web
    environment:
      name: dev
      url: https://nertsal.github.io/drill-above/dev
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web
          destination_dir: dev
